apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  selector:
    app: api
  type: NodePort
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: db-port
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32766