apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  selector:
    app: mysql
  type: NodePort
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32767