apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.secret.db_username | b64enc }}
  password: {{ .Values.secret.db_password | b64enc }}
  root_password: {{ .Values.secret.db_root_password | b64enc }}
