apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: dev
  labels:
    app: db-service
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32767