apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: dev
  labels:
    type: local
    app: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"