apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypteye-web
  namespace: dev
  labels:
    app: crypteye-web
spec:
  selector:
    matchLabels:
      app: crypteye-web
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crypteye-web
    spec:
      containers:
        - name: crypteye-web
          image: crypteye-web:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 256m
              memory: 1000Mi
            limits:
              cpu: 256m
              memory: 1000Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 3000
              name: crypteye-web-port
      restartPolicy: Always
