apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dev
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:latest
          resources:
            requests:
              cpu: 256m
              memory: 1000Mi
            limits:
              cpu: 256m
              memory: 1000Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_name
          ports:
            - containerPort: 3306
              name: db-port
          volumeMounts:
            - name: persistant-storage
              mountPath: /etc/lib/mysql
      volumes:
        - name: persistant-storage
          persistentVolumeClaim:
            claimName: db-pvc
      restartPolicy: Always
